<?php

use Illuminate\Database\Seeder;

class BuyerDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('buyer_details')->insert([
            ['user_id' => 100001,
                'firstname' => 'Buyer1 Transport',
                'lastname' => 'Buyer1',
                'mobile' => 9885202343,
                'landline' => '',
                'contact_email' => 'buyer1logistiks@gmail.com',
                'description' => '',
                'address1' => 'Moosapet',
                'address2' => 'srihari nagar',
                'address3' => 'Hyderabad',
                'pincode' => '500018',
                'lkp_district_id' => 4,
                'lkp_state_id' => 18,
                'lkp_city_id' => '',
                'lkp_location_id' => 65038,
                'alternative_mobile' => '',
                'alternative_email' => '',
                'id_proof' => 4,
                'id_proof_value' => 'ABCDE1234Y',
                'lkp_industry_id' => NULL,
                'principal_place' => 'Hyderabad',
                'name' => '',
                'created_by' => '',
                'created_at' => '',
                'updated_by' => '',
                'updated_at' => '',
                'created_ip' => '',
                'updated_ip' => ''
            ],
            ['user_id' => 100002,
                'firstname' => 'Buyer2 Transport',
                'lastname' => 'Buyer2',
                'mobile' => 7032223732,
                'landline' => '',
                'contact_email' => 'buyer2logistiks@gmail.com',
                'description' => '',
                'address1' => 'kukatpalli',
                'address2' => 'srihari nagar',
                'address3' => 'Hyderabad',
                'pincode' => '500018',
                'lkp_district_id' => 4,
                'lkp_state_id' => 18,
                'lkp_city_id' => '',
                'lkp_location_id' => 65038,
                'alternative_mobile' => '',
                'alternative_email' => '',
                'id_proof' => 4,
                'id_proof_value' => 'ABCDE1234Y',
                'lkp_industry_id' => NULL,
                'principal_place' => 'Hyderabad',
                'name' => '',
                'created_by' => '',
                'created_at' => '',
                'updated_by' => '',
                'updated_at' => '',
                'created_ip' => '',
                'updated_ip' => ''
            ],
            ['user_id' => 100003,
                'firstname' => 'Buyer3 Transport',
                'lastname' => 'Buyer3',
                'mobile' => 9515315208,
                'landline' => '',
                'contact_email' => 'buyer3logistiks@gmail.com',
                'description' => '',
                'address1' => 'Moosapet',
                'address2' => 'srihari nagar',
                'address3' => 'Hyderabad',
                'pincode' => '500018',
                'lkp_district_id' => 4,
                'lkp_state_id' => 18,
                'lkp_city_id' => '',
                'lkp_location_id' => 65038,
                'alternative_mobile' => '',
                'alternative_email' => '',
                'id_proof' => 4,
                'id_proof_value' => 'ABCDE1234Y',
                'lkp_industry_id' => NULL,
                'principal_place' => 'Hyderabad',
                'name' => '',
                'created_by' => '',
                'created_at' => '',
                'updated_by' => '',
                'updated_at' => '',
                'created_ip' => '',
                'updated_ip' => ''
            ],
            ['user_id' => 100004,
                'firstname' => 'Buyer4 Transport',
                'lastname' => 'Buyer4',
                'mobile' => 9948686185,
                'landline' => '',
                'contact_email' => 'buyer4logistiks@gmail.com',
                'description' => '',
                'address1' => 'Moosapet',
                'address2' => 'srihari nagar',
                'address3' => 'Hyderabad',
                'pincode' => '500018',
                'lkp_district_id' => 4,
                'lkp_state_id' => 18,
                'lkp_city_id' => '',
                'lkp_location_id' => 65038,
                'alternative_mobile' => '',
                'alternative_email' => '',
                'id_proof' => 4,
                'id_proof_value' => 'ABCDE1234Y',
                'lkp_industry_id' => NULL,
                'principal_place' => 'Hyderabad',
                'name' => '',
                'created_by' => '',
                'created_at' => '',
                'updated_by' => '',
                'updated_at' => '',
                'created_ip' => '',
                'updated_ip' => ''
            ],
            ['user_id' => 100005,
                'firstname' => 'Buyer5 Transport',
                'lastname' => 'Buyer5',
                'mobile' => 8688496493,
                'landline' => '',
                'contact_email' => 'buyer5logistiks@gmail.com',
                'description' => '',
                'address1' => 'Moosapet',
                'address2' => 'srihari nagar',
                'address3' => 'Hyderabad',
                'pincode' => '500018',
                'lkp_district_id' => 4,
                'lkp_state_id' => 18,
                'lkp_city_id' => '',
                'lkp_location_id' => 65038,
                'alternative_mobile' => '',
                'alternative_email' => '',
                'id_proof' => 4,
                'id_proof_value' => 'ABCDE1234Y',
                'lkp_industry_id' => NULL,
                'principal_place' => 'Hyderabad',
                'name' => '',
                'created_by' => '',
                'created_at' => '',
                'updated_by' => '',
                'updated_at' => '',
                'created_ip' => '',
                'updated_ip' => ''
            ]


        ]);
        echo "Success";

    }
}
