<?php

use Illuminate\Database\Seeder;

class BuyerBusinessDetailsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('buyer_business_details')->insert([
            ['user_id' => 100001,
                'name' => 'Buyer1',
                'lkp_business_type_id' => 1,
                'other_business_type' => '',
                'lkp_country_id' => 1,
                'lkp_state_id' => 1,
                'address' => '',
                'principal_place' => '',
                'pincode' => '',
                'current_turnover' => '',
                'first_year_turnover' => '',
                'second_year_turnover' => '',
                'third_year_turnover' => '',
                'contact_firstname' => 'buyer1',
                'contact_lastname' => '',
                'contact_designation' => '',
                'contact_email' => 'buyer1logistiks@gmail.com',
                'contact_mobile' => '9032560958',
                'contact_landline' => '',
                'gta' => '',
                'tin' => '',
                'service_tax_number' => '',
                'bankname' => '',
                'branchname' => '',
                'in_corporation_file' => '',
                'tin_filepath' => '',
                'gta_filepath' => '',
                'pancard_filepath' => '',
                'service_tax_filepath' => '',
                'central_excise_filepath' => '',
                'sales_tax_filepath' => '',
                'joining_year' => '',
                'established_in' => '',
                'lkp_employee_strength_id' => 1,
                'lkp_industry_id' => 1,
                'mainproduct_services' => '',
                'lkp_speciality_id' => 1,
                'description' => '',
                'logo' => '',
                'main_markets' => '',
                'created_by' => 100001,
                'created_at' => '',
                'created_ip' => '',
                'updated_by' => '',
                'updated_at' => '',
                'updated_ip' => '',


            ],
            ['user_id' => 100002,
                'name' => 'Buyer1',
                'lkp_business_type_id' => 1,
                'other_business_type' => '',
                'lkp_country_id' => 1,
                'lkp_state_id' => 1,
                'address' => '',
                'principal_place' => '',
                'pincode' => '',
                'current_turnover' => '',
                'first_year_turnover' => '',
                'second_year_turnover' => '',
                'third_year_turnover' => '',
                'contact_firstname' => 'buyer2',
                'contact_lastname' => '',
                'contact_designation' => '',
                'contact_email' => 'buyer2logistiks@gmail.com',
                'contact_mobile' => '7032223732',
                'contact_landline' => '',
                'gta' => '',
                'tin' => '',
                'service_tax_number' => '',
                'bankname' => '',
                'branchname' => '',
                'in_corporation_file' => '',
                'tin_filepath' => '',
                'gta_filepath' => '',
                'pancard_filepath' => '',
                'service_tax_filepath' => '',
                'central_excise_filepath' => '',
                'sales_tax_filepath' => '',
                'joining_year' => '',
                'established_in' => '',
                'lkp_employee_strength_id' => 1,
                'lkp_industry_id' => 1,
                'mainproduct_services' => '',
                'lkp_speciality_id' => 1,
                'description' => '',
                'logo' => '',
                'main_markets' => '',
                'created_by' => 100002,
                'created_at' => '',
                'created_ip' => '',
                'updated_by' => '',
                'updated_at' => '',
                'updated_ip' => '',


            ],
            ['user_id' => 100003,
                'name' => 'Buyer1',
                'lkp_business_type_id' => 1,
                'other_business_type' => '',
                'lkp_country_id' => 1,
                'lkp_state_id' => 1,
                'address' => '',
                'principal_place' => '',
                'pincode' => '',
                'current_turnover' => '',
                'first_year_turnover' => '',
                'second_year_turnover' => '',
                'third_year_turnover' => '',
                'contact_firstname' => 'buyer3',
                'contact_lastname' => '',
                'contact_designation' => '',
                'contact_email' => 'buyer3logistiks@gmail.com',
                'contact_mobile' => '8688496493',
                'contact_landline' => '',
                'gta' => '',
                'tin' => '',
                'service_tax_number' => '',
                'bankname' => '',
                'branchname' => '',
                'in_corporation_file' => '',
                'tin_filepath' => '',
                'gta_filepath' => '',
                'pancard_filepath' => '',
                'service_tax_filepath' => '',
                'central_excise_filepath' => '',
                'sales_tax_filepath' => '',
                'joining_year' => '',
                'established_in' => '',
                'lkp_employee_strength_id' => 1,
                'lkp_industry_id' => 1,
                'mainproduct_services' => '',
                'lkp_speciality_id' => 1,
                'description' => '',
                'logo' => '',
                'main_markets' => '',
                'created_by' => 100003,
                'created_at' => '',
                'created_ip' => '',
                'updated_by' => '',
                'updated_at' => '',
                'updated_ip' => '',


            ],
            ['user_id' => 100004,
                'name' => 'Buyer1',
                'lkp_business_type_id' => 1,
                'other_business_type' => '',
                'lkp_country_id' => 1,
                'lkp_state_id' => 1,
                'address' => '',
                'principal_place' => '',
                'pincode' => '',
                'current_turnover' => '',
                'first_year_turnover' => '',
                'second_year_turnover' => '',
                'third_year_turnover' => '',
                'contact_firstname' => 'buyer4',
                'contact_lastname' => '',
                'contact_designation' => '',
                'contact_email' => 'buyer4logistiks@gmail.com',
                'contact_mobile' => '7032223732',
                'contact_landline' => '',
                'gta' => '',
                'tin' => '',
                'service_tax_number' => '',
                'bankname' => '',
                'branchname' => '',
                'in_corporation_file' => '',
                'tin_filepath' => '',
                'gta_filepath' => '',
                'pancard_filepath' => '',
                'service_tax_filepath' => '',
                'central_excise_filepath' => '',
                'sales_tax_filepath' => '',
                'joining_year' => '',
                'established_in' => '',
                'lkp_employee_strength_id' => 1,
                'lkp_industry_id' => 1,
                'mainproduct_services' => '',
                'lkp_speciality_id' => 1,
                'description' => '',
                'logo' => '',
                'main_markets' => '',
                'created_by' => 100004,
                'created_at' => '',
                'created_ip' => '',
                'updated_by' => '',
                'updated_at' => '',
                'updated_ip' => '',


            ],
            ['user_id' => 100005,
                'name' => 'Buyer1',
                'lkp_business_type_id' => 1,
                'other_business_type' => '',
                'lkp_country_id' => 1,
                'lkp_state_id' => 1,
                'address' => '',
                'principal_place' => '',
                'pincode' => '',
                'current_turnover' => '',
                'first_year_turnover' => '',
                'second_year_turnover' => '',
                'third_year_turnover' => '',
                'contact_firstname' => 'buyer5',
                'contact_lastname' => '',
                'contact_designation' => '',
                'contact_email' => 'buyer5logistiks@gmail.com',
                'contact_mobile' => '7032223732',
                'contact_landline' => '',
                'gta' => '',
                'tin' => '',
                'service_tax_number' => '',
                'bankname' => '',
                'branchname' => '',
                'in_corporation_file' => '',
                'tin_filepath' => '',
                'gta_filepath' => '',
                'pancard_filepath' => '',
                'service_tax_filepath' => '',
                'central_excise_filepath' => '',
                'sales_tax_filepath' => '',
                'joining_year' => '',
                'established_in' => '',
                'lkp_employee_strength_id' => 1,
                'lkp_industry_id' => 1,
                'mainproduct_services' => '',
                'lkp_speciality_id' => 1,
                'description' => '',
                'logo' => '',
                'main_markets' => '',
                'created_by' => 100005,
                'created_at' => '',
                'created_ip' => '',
                'updated_by' => '',
                'updated_at' => '',
                'updated_ip' => '',


            ]

        ]);
        echo "Success";

    }
}
