<?php

use Illuminate\Database\Seeder;

class CodeListSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('shp_codelist')->truncate();
        DB::table('shp_codelist')->insert([

            ['entity' => 'MessageType', 'field' => 'code', 'value' => '8', 'description' => 'Community', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'MessageType', 'field' => 'code', 'value' => '7', 'description' => 'Contracts', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'MessageType', 'field' => 'code', 'value' => '1', 'description' => 'General', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'MessageType', 'field' => 'code', 'value' => '9', 'description' => 'Network', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'MessageType', 'field' => 'code', 'value' => '3', 'description' => 'Orders', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'MessageType', 'field' => 'code', 'value' => '2', 'description' => 'Posts', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Services', 'field' => 'code', 'value' => '22', 'description' => 'FCL', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Country', 'field' => 'code', 'value' => 'India', 'description' => 'India', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Country', 'field' => 'isocode', 'value' => 'India', 'description' => 'IN', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Country', 'field' => 'currency', 'value' => 'India', 'description' => 'INR', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Country', 'field' => 'capital', 'value' => 'India', 'description' => 'Delhi', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Country', 'field' => 'tz', 'value' => 'India', 'description' => 'UTC+5:30', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],

            ['entity' => 'Country', 'field' => 'code', 'value' => 'America', 'description' => 'United States of America', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Country', 'field' => 'isocode', 'value' => 'America', 'description' => 'US', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Country', 'field' => 'currency', 'value' => 'America', 'description' => 'USD', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Country', 'field' => 'capital', 'value' => 'America', 'description' => 'Washington', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Country', 'field' => 'tz', 'value' => 'America', 'description' => 'UTC-9:00', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],


            ['entity' => 'RoutingType', 'field' => 'code', 'value' => 'Direct', 'description' => 'Direct', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'RoutingType', 'field' => 'code', 'value' => 'Via', 'description' => 'Via', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '20 Dry Standard', 'description' => '20 Dry Standard', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '20 Dry Standard', 'description' => 'none', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '20 Dry Standard', 'description' => '26', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '40 Dry Standard', 'description' => '40 Dry Standard', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '40 Dry Standard', 'description' => 'none', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '40 Dry Standard', 'description' => '28', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '40 High cube Standard', 'description' => '40 High cube Standard', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '40 High cube Standard', 'description' => 'none', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '40 High cube Standard', 'description' => '28', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '45 Dry High', 'description' => '45 Dry High', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '45 Dry High', 'description' => 'none', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '45 Dry High', 'description' => '28', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '20 Heavy Duty', 'description' => '20 Heavy Duty', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '20 Heavy Duty', 'description' => 'none', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '20 Heavy Duty', 'description' => '28', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '20 GOH', 'description' => '20 GOH', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '20 GOH', 'description' => 'GOH', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '20 GOH', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '40 GOH', 'description' => '40 GOH', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '40 GOH', 'description' => 'GOH', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '40 GOH', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '20 Reefer Standard', 'description' => '20 Reefer Standard', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '20 Reefer Standard', 'description' => 'TemperatureControl', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '20 Reefer Standard', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '40 Reefer High', 'description' => '40 Reefer High', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '40 Reefer High', 'description' => 'TemperatureControl', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '40 Reefer High', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '20 Flat Rack', 'description' => '20 Flat Rack', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '20 Flat Rack', 'description' => 'Oversized', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '20 Flat Rack', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '40 Flat Rack Standard', 'description' => '40 Flat Rack Standard', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '40 Flat Rack Standard', 'description' => 'Oversized', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '40 Flat Rack Standard', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '40 Flat Rack High', 'description' => '40 Flat Rack High', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '40 Flat Rack High', 'description' => 'Oversized', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '40 Flat Rack High', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '20 Open top', 'description' => '20 Open top', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '20 Open top', 'description' => 'Oversized', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '20 Open top', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '40 Open top', 'description' => '40 Open top', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '40 Open top', 'description' => 'Oversized', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '40 Open top', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '40 High open top', 'description' => '40 High open top', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '40 High open top', 'description' => 'Oversized', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '40 High open top', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '20 Tank', 'description' => '20 Tank', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '20 Tank', 'description' => 'Tanktainer', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '20 Tank', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => '40 Tank', 'description' => '40 Tank', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => '40 Tank', 'description' => 'Tanktainer', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => '40 Tank', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => 'MAFI 20', 'description' => 'MAFI 20', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => 'MAFI 20', 'description' => 'RORO', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => 'MAFI 20', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => 'MAFI 40', 'description' => 'MAFI 40', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => 'MAFI 40', 'description' => 'RORO', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => 'MAFI 40', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => 'MAFI 45', 'description' => 'MAFI 45', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => 'MAFI 45', 'description' => 'RORO', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => 'MAFI 45', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'code', 'value' => 'MAFI 60', 'description' => 'MAFI 60', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'specialCondition', 'value' => 'MAFI 60', 'description' => 'RORO', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ContainerTypes', 'field' => 'payload', 'value' => 'MAFI 60', 'description' => '', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'RCContainerTypes', 'field' => 'code', 'value' => '20 Dry Standard', 'description' => '20 Dry Standard', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'RCContainerTypes', 'field' => 'code', 'value' => '40 Dry Standard', 'description' => '40 Dry Standard', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'RCContainerTypes', 'field' => 'code', 'value' => '40 High cube Standard', 'description' => '40 High cube Standard', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'RCContainerTypes', 'field' => 'code', 'value' => '45 Dry High', 'description' => '45 Dry High', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'RCContainerTypes', 'field' => 'code', 'value' => '20 Heavy Duty', 'description' => '20 Heavy Duty', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],

            ['entity' => 'BuyerSearchContainerTypes', 'field' => 'code', 'value' => '20 Dry Standard', 'description' => '20 Dry Standard', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'BuyerSearchContainerTypes', 'field' => 'payload', 'value' => '20 Dry Standard', 'description' => '26', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'BuyerSearchContainerTypes', 'field' => 'code', 'value' => '40 Dry Standard', 'description' => '40 Dry Standard', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'BuyerSearchContainerTypes', 'field' => 'payload', 'value' => '40 Dry Standard', 'description' => '28', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'BuyerSearchContainerTypes', 'field' => 'code', 'value' => '40 High cube Standard', 'description' => '40 High cube Standard', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'BuyerSearchContainerTypes', 'field' => 'payload', 'value' => '40 High cube Standard', 'description' => '28', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'BuyerSearchContainerTypes', 'field' => 'code', 'value' => '45 Dry High', 'description' => '45 Dry High', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'BuyerSearchContainerTypes', 'field' => 'payload', 'value' => '45 Dry High', 'description' => '28', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Air conditioners and Chillers', 'description' => 'Air conditioners and Chillers', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Automobiles', 'description' => 'Automobiles', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Bicycle', 'description' => 'Bicycle', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Boiler and Accessories', 'description' => 'Boiler and Accessories', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Cattle feed products', 'description' => 'Cattle feed products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Cements', 'description' => 'Cements', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Chemicals/ Liquid chemicals', 'description' => 'Chemicals/ Liquid chemicals', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Clock, watches', 'description' => 'Clock, watches', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Coal/Bulk', 'description' => 'Coal/Bulk', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Coffee, Tea', 'description' => 'Coffee, Tea', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Confectionary/Food &amp; beverages', 'description' => 'Confectionary/Food & beverages', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Containers', 'description' => 'Containers', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Cotton/Textiles/garments/Yarn', 'description' => 'Cotton/Textiles/garments/Yarn', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Crude Oil /Petroleum Products', 'description' => 'Crude Oil /Petroleum Products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Edible Oil', 'description' => 'Edible Oil', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Electrical goods/ Transfomers', 'description' => 'Electrical goods/ Transfomers', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Electronic Goods', 'description' => 'Electronic Goods', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Empty Cylinders', 'description' => 'Empty Cylinders', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Engineering Goods', 'description' => 'Engineering Goods', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Fertilizers', 'description' => 'Fertilizers', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'FMCG', 'description' => 'FMCG', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Frozen items', 'description' => 'Frozen items', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Fruits,Vegetables, Perishables', 'description' => 'Fruits,Vegetables, Perishables', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Furnace equipments or refractories', 'description' => 'Furnace equipments or refractories', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Glass,bulbs,Fragile items', 'description' => 'Glass,bulbs,Fragile items', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Grains/Species', 'description' => 'Grains/Species', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Handicrafts', 'description' => 'Handicrafts', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Hardware Items', 'description' => 'Hardware Items', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Household goods', 'description' => 'Household goods', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Jute/Gunny bags/coir products', 'description' => 'Jute/Gunny bags/coir products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Leather Goods', 'description' => 'Leather Goods', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Liquor/Cigarettes/ Other Tobaco Products', 'description' => 'Liquor/Cigarettes/ Other Tobaco Products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Load Type (Any)', 'description' => 'Load Type (Any)', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Logistics', 'description' => 'Logistics', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Machinery/Tools', 'description' => 'Machinery/Tools', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Matches/Explosv', 'description' => 'Matches/Explosv', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Medical Equipments', 'description' => 'Medical Equipments', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Metalaic fabrication materials', 'description' => 'Metalaic fabrication materials', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Metalware', 'description' => 'Metalware', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Milk & Dairy Products', 'description' => 'Milk & Dairy Products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Minerals', 'description' => 'Minerals', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Musical Instruments', 'description' => 'Musical Instruments', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Non metal elements like carbon', 'description' => 'Non metal elements like carbon', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Office Equipments', 'description' => 'Office Equipments', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Packaging prodicts', 'description' => 'Packaging prodicts', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Paints', 'description' => 'Paints', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Paper products / stationary items', 'description' => 'Paper products / stationary items', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Perfume & cosmetic Goods, clenaing & Toiletory ite', 'description' => 'Perfume & cosmetic Goods, clenaing & Toiletory ite', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Pharmachutical Products', 'description' => 'Pharmachutical Products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Plastic / Rubber / Tyres goods', 'description' => 'Plastic / Rubber / Tyres goods', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Precious & Semi Precious stones', 'description' => 'Precious & Semi Precious stones', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Retail Traders', 'description' => 'Retail Traders', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Rice/Bulk', 'description' => 'Rice/Bulk', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Sanitaryware/Abrasives/Granites/Marbles/Tiles', 'description' => 'Sanitaryware/Abrasives/Granites/Marbles/Tiles', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Sports Goods & wellness Equipments', 'description' => 'Sports Goods & wellness Equipments', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Structural Material including Pipes', 'description' => 'Structural Material including Pipes', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Sugar', 'description' => 'Sugar', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Timber logs', 'description' => 'Timber logs', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Toys, Games, Childrens Products', 'description' => 'Toys, Games, Childrens Products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Utensils & equipments related to Hotel Industry', 'description' => 'Utensils & equipments related to Hotel Industry', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'Commodity', 'field' => 'code', 'value' => 'Wood/Furniture / Capex items', 'description' => 'Wood/Furniture / Capex items', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'Ocean Freight', 'description' => 'Ocean Freight', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'BAF', 'description' => 'BAF', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'Container Imbalance surcharge', 'description' => 'Container Imbalance surcharge', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'Emergency Risk Surcharge', 'description' => 'Emergency Risk Surcharge', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'Low Sulphar Surcharge', 'description' => 'Low Sulphar Surcharge', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'Peak Seson Surcharge', 'description' => 'Peak Seson Surcharge', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'Rate Restoration surcharge', 'description' => 'Rate Restoration surcharge', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'General Rate Increase', 'description' => 'General Rate Increase', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'Aden Gulf Surcharge', 'description' => 'Aden Gulf Surcharge', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'Suez Canal Surchage', 'description' => 'Suez Canal Surchage', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'OT - Surcharge', 'description' => 'OT - Surcharge', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'Standard Bunker Adjustment Factor', 'description' => 'Standard Bunker Adjustment Factor', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'Currency Adjustment Factor', 'description' => 'Currency Adjustment Factor', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'Chasis Usage Charge', 'description' => 'Chasis Usage Charge', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FreightCharges', 'field' => 'code', 'value' => 'Destination Delivery', 'description' => 'Destination Delivery', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Agency Fee', 'description' => 'Agency Fee', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Handling Fee', 'description' => 'Handling Fee', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Miscellaneous', 'description' => 'Miscellaneous', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Seal Verification Charges - Ground', 'description' => 'Seal Verification Charges - Ground', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Seal Verification Charges - On Wheel', 'description' => 'Seal Verification Charges - On Wheel', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Shipping Bill Fee', 'description' => 'Shipping Bill Fee', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Shipping Bill Fee (More than 5 containers)', 'description' => 'Shipping Bill Fee (More than 5 containers)', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Open examination charges - On Wheel', 'description' => 'Open examination charges - On Wheel', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Open examination charges - Ground', 'description' => 'Open examination charges - Ground', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'On Wheel Manual Stuffing', 'description' => 'On Wheel Manual Stuffing', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],

            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'On Wheel Mechanical', 'description' => 'On Wheel Mechanical', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Ground Stuffing Manual', 'description' => 'Ground Stuffing Manual', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Ground Stuffing Mechanial', 'description' => 'Ground Stuffing Mechanial', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Laden Lo/Lo', 'description' => 'Laden Lo/Lo', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Empty Lo/Lo', 'description' => 'Empty Lo/Lo', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Exmpty Container Storage - Export', 'description' => 'Exmpty Container Storage - Export', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Weighment charges', 'description' => 'Weighment charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Fuel Surcharge', 'description' => 'Fuel Surcharge', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Energy Surcharge', 'description' => 'Energy Surcharge', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Shifting Laden In CFS', 'description' => 'Shifting Laden In CFS', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Reefer Plug In Charges - CFS', 'description' => 'Reefer Plug In Charges - CFS', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Reefer Plug In Charges - Port', 'description' => 'Reefer Plug In Charges - Port', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Genset Charges', 'description' => 'Genset Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Reefer Monitor Charges', 'description' => 'Reefer Monitor Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Import Clearance Fee', 'description' => 'Import Clearance Fee', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Filing Assesment Fee', 'description' => 'Filing Assesment Fee', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Examination Fee', 'description' => 'Examination Fee', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Service Fee', 'description' => 'Service Fee', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Escorting Charges', 'description' => 'Escorting Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Cleaning Charges', 'description' => 'Cleaning Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Container Maintainence Charges', 'description' => 'Container Maintainence Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Survey Charges', 'description' => 'Survey Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'ISPS Charges', 'description' => 'ISPS Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Manifest Charges', 'description' => 'Manifest Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'AMS', 'description' => 'AMS', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Halting Charges', 'description' => 'Halting Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'SSR Charges', 'description' => 'SSR Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'CFS Storage charges', 'description' => 'CFS Storage charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Fumigation Charges', 'description' => 'Fumigation Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Exchange B/L Fee', 'description' => 'Exchange B/L Fee', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Surrender Fee', 'description' => 'Surrender Fee', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'GOH Surcharge', 'description' => 'GOH Surcharge', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Over weight surcharge', 'description' => 'Over weight surcharge', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Crane Charges', 'description' => 'Crane Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Intercarting Charges', 'description' => 'Intercarting Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Port Charges', 'description' => 'Port Charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Stuffing & Lashing charges', 'description' => 'Stuffing & Lashing charges', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Origin Transportation', 'description' => 'Origin Transportation', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Destination Transportation', 'description' => 'Destination Transportation', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'THC  - Origin', 'description' => 'THC  - Origin', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'THC - Destination', 'description' => 'THC - Destination', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Documentation Fee - Origin', 'description' => 'Documentation Fee - Origin', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Documentation Fee - Destination', 'description' => 'Documentation Fee - Destination', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'Delivery Order Fee', 'description' => 'Delivery Order Fee', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'LocalCharges', 'field' => 'code', 'value' => 'House B/L Fee', 'description' => 'House B/L Fee', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'TrackingType', 'field' => 'code', 'value' => 'Milestone', 'description' => 'Milestone', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
// ['entity' =>  'TrackingType',  'field' => 'code', 'value' => 'Real time',  'description' =>'Real time', 'child_entity' =>'', 'created_by'=>'1' ,'is_active'=>'1'  ],
            ['entity' => 'TrackingType', 'field' => 'code', 'value' => 'No Tracking', 'description' => 'No Tracking', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'SailingFrequency', 'field' => 'code', 'value' => 'Monthly', 'description' => 'Monthly', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'SailingFrequency', 'field' => 'code', 'value' => 'Fortnightly', 'description' => 'Fortnightly', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'SailingFrequency', 'field' => 'code', 'value' => 'Weekly Twice', 'description' => 'Weekly Twice', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'SailingFrequency', 'field' => 'code', 'value' => 'Weekly', 'description' => 'Weekly', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Air conditioners and Chillers', 'description' => 'Air conditioners and Chillers', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Automobiles', 'description' => 'Automobiles', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Bicycle', 'description' => 'Bicycle', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Boiler and Accessories', 'description' => 'Boiler and Accessories', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Cattle feed products', 'description' => 'Cattle feed products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Cements', 'description' => 'Cements', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Chemicals/ Liquid chemicals', 'description' => 'Chemicals/ Liquid chemicals', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Clock, watches', 'description' => 'Clock, watches', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Coal/Bulk', 'description' => 'Coal/Bulk', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Coffee, Tea', 'description' => 'Coffee, Tea', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Confectionary/Food &amp; beverages', 'description' => 'Confectionary/Food & beverages', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Containers', 'description' => 'Containers', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Cotton/Textiles/garments/Yarn', 'description' => 'Cotton/Textiles/garments/Yarn', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Crude Oil /Petroleum Products', 'description' => 'Crude Oil /Petroleum Products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Edible Oil', 'description' => 'Edible Oil', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Electrical goods/ Transfomers', 'description' => 'Electrical goods/ Transfomers', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Electronic Goods', 'description' => 'Electronic Goods', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Empty Cylinders', 'description' => 'Empty Cylinders', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Engineering Goods', 'description' => 'Engineering Goods', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Fertilizers', 'description' => 'Fertilizers', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'FMCG', 'description' => 'FMCG', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Frozen items', 'description' => 'Frozen items', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Fruits,Vegetables, Perishables', 'description' => 'Fruits,Vegetables, Perishables', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Furnace equipments or refractories', 'description' => 'Furnace equipments or refractories', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Glass,bulbs,Fragile items', 'description' => 'Glass,bulbs,Fragile items', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Grains/Species', 'description' => 'Grains/Species', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Handicrafts', 'description' => 'Handicrafts', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Hardware Items', 'description' => 'Hardware Items', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Household goods', 'description' => 'Household goods', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Jute/Gunny bags/coir products', 'description' => 'Jute/Gunny bags/coir products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Leather Goods', 'description' => 'Leather Goods', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Liquor/Cigarettes/ Other Tobaco Products', 'description' => 'Liquor/Cigarettes/ Other Tobaco Products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Load Type (Any)', 'description' => 'Load Type (Any)', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Logistics', 'description' => 'Logistics', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Machinery/Tools', 'description' => 'Machinery/Tools', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Matches/Explosv', 'description' => 'Matches/Explosv', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Medical Equipments', 'description' => 'Medical Equipments', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Metalaic fabrication materials', 'description' => 'Metalaic fabrication materials', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Metalware', 'description' => 'Metalware', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Milk & Dairy Products', 'description' => 'Milk & Dairy Products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Minerals', 'description' => 'Minerals', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Musical Instruments', 'description' => 'Musical Instruments', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Non metal elements like carbon', 'description' => 'Non metal elements like carbon', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Office Equipments', 'description' => 'Office Equipments', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Packaging prodicts', 'description' => 'Packaging prodicts', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Paints', 'description' => 'Paints', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Paper products / stationary items', 'description' => 'Paper products / stationary items', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Perfume & cosmetic Goods, clenaing & Toiletory ite', 'description' => 'Perfume & cosmetic Goods, clenaing & Toiletory ite', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Pharmachutical Products', 'description' => 'Pharmachutical Products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Plastic / Rubber / Tyres goods', 'description' => 'Plastic / Rubber / Tyres goods', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Precious & Semi Precious stones', 'description' => 'Precious & Semi Precious stones', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Retail Traders', 'description' => 'Retail Traders', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Rice/Bulk', 'description' => 'Rice/Bulk', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Sanitaryware/Abrasives/Granites/Marbles/Tiles', 'description' => 'Sanitaryware/Abrasives/Granites/Marbles/Tiles', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Sports Goods & wellness Equipments', 'description' => 'Sports Goods & wellness Equipments', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Structural Material including Pipes', 'description' => 'Structural Material including Pipes', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Sugar', 'description' => 'Sugar', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Timber logs', 'description' => 'Timber logs', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Toys, Games, Childrens Products', 'description' => 'Toys, Games, Childrens Products', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Utensils & equipments related to Hotel Industry', 'description' => 'Utensils & equipments related to Hotel Industry', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ProductType', 'field' => 'code', 'value' => 'Wood/Furniture / Capex items', 'description' => 'Wood/Furniture / Capex items', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass', 'field' => 'code', 'value' => '1', 'description' => 'description 1', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass', 'field' => 'code', 'value' => '2', 'description' => 'description 2', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass', 'field' => 'code', 'value' => '3', 'description' => 'description 3', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass', 'field' => 'code', 'value' => '4', 'description' => 'description 4', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass', 'field' => 'code', 'value' => '5', 'description' => 'description 5', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass', 'field' => 'code', 'value' => '6', 'description' => 'description 6', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass', 'field' => 'code', 'value' => '7', 'description' => 'description 7', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass', 'field' => 'code', 'value' => '8', 'description' => 'description 8', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass', 'field' => 'code', 'value' => '9', 'description' => 'description 9', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@1', 'field' => 'code', 'value' => '1.1', 'description' => '1.1', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@1', 'field' => 'code', 'value' => '1.2', 'description' => '1.2', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@1', 'field' => 'code', 'value' => '1.3', 'description' => '1.3', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@1', 'field' => 'code', 'value' => '1.4', 'description' => '1.4', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@1', 'field' => 'code', 'value' => '1.5', 'description' => '1.5', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@1', 'field' => 'code', 'value' => '1.6', 'description' => '1.6', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@2', 'field' => 'code', 'value' => '2.1', 'description' => '2.1', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@2', 'field' => 'code', 'value' => '2.2', 'description' => '2.2', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@2', 'field' => 'code', 'value' => '2.3', 'description' => '2.3', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@4', 'field' => 'code', 'value' => '4.1', 'description' => '4.1', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@4', 'field' => 'code', 'value' => '4.2', 'description' => '4.2', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@4', 'field' => 'code', 'value' => '4.3', 'description' => '4.3', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@5', 'field' => 'code', 'value' => '5.1', 'description' => '5.1', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@5', 'field' => 'code', 'value' => '5.2', 'description' => '5.2', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@6', 'field' => 'code', 'value' => '6.1', 'description' => '6.1', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'IMOClass@6', 'field' => 'code', 'value' => '6.2', 'description' => '6.2', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingGroup', 'field' => 'code', 'value' => 'I', 'description' => 'I', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingGroup', 'field' => 'code', 'value' => 'II', 'description' => 'II', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingGroup', 'field' => 'code', 'value' => 'III', 'description' => 'III', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'CustomImportBillType', 'field' => 'code', 'value' => 'Home consumption', 'description' => 'Home consumption', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'CustomImportBillType', 'field' => 'code', 'value' => 'Warehouing', 'description' => 'Warehouing', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'CustomImportBillType', 'field' => 'code', 'value' => 'Ex Bond', 'description' => 'Ex Bond', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'CustomImportBillType', 'field' => 'code', 'value' => 'SEZ Bill', 'description' => 'SEZ Bill', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'CustomImportBillType', 'field' => 'code', 'value' => 'Other', 'description' => 'Other (Specify)', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ShippingBillType', 'field' => 'code', 'value' => 'Free Shiping bill', 'description' => 'Free Shiping bill', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ShippingBillType', 'field' => 'code', 'value' => 'Drawback Bill', 'description' => 'Drawback Bill', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ShippingBillType', 'field' => 'code', 'value' => 'DEPB Bill', 'description' => 'DEPB Bill', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ShippingBillType', 'field' => 'code', 'value' => 'Ex Bond', 'description' => 'Ex Bond', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ShippingBillType', 'field' => 'code', 'value' => 'SEZ Bill', 'description' => 'SEZ Bill', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ShippingBillType', 'field' => 'code', 'value' => 'Duty Bill', 'description' => 'Duty Bill', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ShippingBillType', 'field' => 'code', 'value' => 'Other', 'description' => 'Other (Specify)', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'MeasurementUnit', 'field' => 'code', 'value' => 'CM', 'description' => 'CM', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'MeasurementUnit', 'field' => 'code', 'value' => 'Feet', 'description' => 'Feet', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'MeasurementUnit', 'field' => 'code', 'value' => 'Inches', 'description' => 'Inches', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'MeasurementUnit', 'field' => 'code', 'value' => 'Meter', 'description' => 'Meter', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'TrailerTypes', 'field' => 'code', 'value' => '20 FT Single Axle', 'description' => '20 FT Single Axle', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'TrailerTypes', 'field' => 'code', 'value' => '20 FT Double Axle', 'description' => '20 FT Double Axle', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'TrailerTypes', 'field' => 'code', 'value' => '40 FT Single Axle', 'description' => '40 FT Single Axle', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'TrailerTypes', 'field' => 'code', 'value' => '40 FT Double Axle', 'description' => '40 FT Double Axle', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'TrailerTypes', 'field' => 'code', 'value' => '40 FT Triple Axle', 'description' => '40 FT Triple Axle', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'TrailerTypes', 'field' => 'code', 'value' => '20 FT Low Bed', 'description' => '20 FT Low Bed', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'TrailerTypes', 'field' => 'code', 'value' => '40 FT Low Bed', 'description' => '40 FT Low Bed', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'TrailerTypes', 'field' => 'code', 'value' => '20 FT Semi Low bed', 'description' => '20 FT Semi Low bed', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'TrailerTypes', 'field' => 'code', 'value' => '40 FT Semi Low bed', 'description' => '40 FT Semi Low bed', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'TrailerTypes', 'field' => 'code', 'value' => '20 FT Reefer Trailer', 'description' => '20 FT Reefer Trailer', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'TrailerTypes', 'field' => 'code', 'value' => '40 FT Reefer Trailer', 'description' => '40 FT Reefer Trailer', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ReturnableCategory', 'field' => 'code', 'value' => 'Repair', 'description' => 'Repair', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ReturnableCategory', 'field' => 'code', 'value' => 'Exhibition', 'description' => 'Exhibition', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ReturnableCategory', 'field' => 'code', 'value' => 'Testing', 'description' => 'Testing', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ReturnableCategory', 'field' => 'code', 'value' => 'R & D', 'description' => 'R & D', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ReturnableCategory', 'field' => 'code', 'value' => 'Other', 'description' => 'Other (Specify)', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],

            ['entity' => 'INCOTerms', 'field' => 'code', 'value' => 'DAP', 'description' => 'Delvered At Place', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'INCOTerms', 'field' => 'Remarks', 'value' => 'DAP', 'description' => 'Apply', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'INCOTerms', 'field' => 'code', 'value' => 'DDP', 'description' => 'Deliverey Duty Paid', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'INCOTerms', 'field' => 'Remarks', 'value' => 'DDP', 'description' => 'Apply', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'INCOTerms', 'field' => 'code', 'value' => 'CFR', 'description' => 'Cost and Freight', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'INCOTerms', 'field' => 'Remarks', 'value' => 'CFR', 'description' => 'Apply', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'INCOTerms', 'field' => 'code', 'value' => 'CIF', 'description' => 'Cost Insurance and Freight', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'INCOTerms', 'field' => 'Remarks', 'value' => 'CIF', 'description' => 'CIF', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],

            ['entity' => 'FclBuyerPostDocs', 'field' => 'code', 'value' => 'Invoice', 'description' => 'Invoice', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FclBuyerPostDocs', 'field' => 'code', 'value' => 'Packing List', 'description' => 'Packing List', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FclBuyerPostDocs', 'field' => 'code', 'value' => 'Export Bills', 'description' => 'Export Bills', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FclSellerPostDocs', 'field' => 'code', 'value' => 'Invoice', 'description' => 'Invoice', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FclSellerPostDocs', 'field' => 'code', 'value' => 'Packing List', 'description' => 'Packing List', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'FclSellerPostDocs', 'field' => 'code', 'value' => 'Export Bills', 'description' => 'Export Bills', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],

            ['entity' => 'ServiceSubType', 'field' => 'code', 'value' => 'Port to Port', 'description' => 'Port to Port', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ServiceSubType', 'field' => 'code', 'value' => 'Port to Door', 'description' => 'Port to Door', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ServiceSubType', 'field' => 'code', 'value' => 'Door to Port', 'description' => 'Door to Port', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'ServiceSubType', 'field' => 'code', 'value' => 'Door to Door', 'description' => 'Door to Door', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],

            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Corrugated Carton', 'description' => 'Corrugated Carton', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Crates', 'description' => 'Crates', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Pallets', 'description' => 'Pallets', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Shrink Wrap', 'description' => 'Shrink Wrap', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Polythene Bags', 'description' => 'Polythene Bags', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Steel Drums', 'description' => 'Steel Drums', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Barrels', 'description' => 'Barrels', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Rigid Plastic Containers', 'description' => 'Rigid Plastic Containers', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Blister Packs', 'description' => 'Blister Packs', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Fragile', 'description' => 'Fragile', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Skin Packaging', 'description' => 'Skin Packaging', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Bulk / Open', 'description' => 'Bulk / Open', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Others - Specify', 'description' => 'Others - Specify', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Thermocol Pack', 'description' => 'Thermocol Pack', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
            ['entity' => 'PackagingType', 'field' => 'code', 'value' => 'Gunny Bags', 'description' => 'Gunny Bags', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],

//Delete following Feature set later
            ['entity' => 'Features', 'field' => 'code', 'value' => 'Milestone', 'description' => 'Milestone', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],
//['entity' =>  'Features',  'field' => 'code', 'value' => 'Real time',  'description' =>'Real time', 'child_entity' =>'', 'created_by'=>'1' ,'is_active'=>'1'  ],
            ['entity' => 'Features', 'field' => 'code', 'value' => 'No Tracking', 'description' => 'No Tracking', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],


            ['entity' => 'CharterType', 'field' => 'code', 'value' => 'Passenger AirCraft', 'description' => 'Passenger AirCraft', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],

            ['entity' => 'CharterType', 'field' => 'code', 'value' => 'Cargo AirCraft', 'description' => 'Cargo AirCraft', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],

            ['entity' => 'CharterType', 'field' => 'code', 'value' => 'Private Jet', 'description' => 'Private Jet', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],

            ['entity' => 'CharterType', 'field' => 'code', 'value' => 'Helicopter', 'description' => 'Helicopter', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],


            ['entity' => 'PriceType', 'field' => 'code', 'value' => 'Competitive', 'description' => 'Competitive', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1'],

            ['entity' => 'PriceType', 'field' => 'code', 'value' => 'Firm Price', 'description' => 'Firm Price', 'child_entity' => '', 'created_by' => '1', 'is_active' => '1']
        ]);

        echo "success";


    }
}
