
--  Shipping Services Start -------------------
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (22,3,'Ocean FCL',0,'International','Container','images/log-icons/FCL.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (23,3,'Ocean LCL',0,'International','Container','images/log-icons/LCL.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (24,3,'Dry',0,'International','Bulk','images/log-icons/Dry.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (25,3,'Liquid',0,'International','Bulk','images/log-icons/Liquid.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (26,3,'Break Bulk',0,'International','Bulk','images/log-icons/BreakBulkStatic.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (27,3,'Tyre Mounted',0,'International','RoRo','images/log-icons/TyreMounted.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (28,3,'Chain or Track mounted',0,'International','RoRo','images/log-icons/ChainTrack.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (29,3,'MAFI',0,'International','RoRo','images/log-icons/RoRoMAFI.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (30,3,'Bulk',0,'Domestic','Coastal','images/log-icons/CostalBulk.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (31,3,'Container',0,'Domestic','Coastal','images/log-icons/CostalContainer.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (32,3,'Ro-Ro',0,'Domestic','Coastal','images/log-icons/CostalRoRo.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (33,4,'Domestic',0,'Air','Domestic','images/log-icons/AirDomestic.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (34,4,'International',0,'Air','International','images/log-icons/AirInternational.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (35,5,'Cross-border',0,'Cross-border','Domestic','images/log-icons/Crossborder.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (36,6,'Port services',0,'Port services','Port services','images/log-icons/MarinePort.png',1,'2017-03-31 07:59:23');
INSERT INTO `lkp_services` (`id`,`lkp_invoice_service_group_id`,`service_name`,`subcategory_id`,`service_crumb_name`,`group_name`,`service_image_path`,`is_active`,`created_at`) VALUES (37,6,'Marine services',0,'Marine services','Marine services','images/log-icons/MarinePort.png',1,'2017-03-31 07:59:23');

-----Shipping Services End--------------------