<?php

use Illuminate\Database\Seeder;

class UsersSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('buyer_business_details')->where("user_id", "100001")->delete();
        DB::table('buyer_business_details')->where("user_id", "100002")->delete();
        DB::table('buyer_business_details')->where("user_id", "100003")->delete();
        DB::table('buyer_business_details')->where("user_id", "100004")->delete();
        DB::table('buyer_business_details')->where("user_id", "100005")->delete();

        DB::table('buyer_details')->where("user_id", "100001")->delete();
        DB::table('buyer_details')->where("user_id", "100002")->delete();
        DB::table('buyer_details')->where("user_id", "100003")->delete();
        DB::table('buyer_details')->where("user_id", "100004")->delete();
        DB::table('buyer_details')->where("user_id", "100005")->delete();

        DB::table('seller_details')->where("user_id", "100006")->delete();
        DB::table('seller_details')->where("user_id", "100007")->delete();
        DB::table('seller_details')->where("user_id", "100008")->delete();
        DB::table('seller_details')->where("user_id", "100009")->delete();
        DB::table('seller_details')->where("user_id", "100010")->delete();

        DB::table('users')->where("id", "100001")->delete();
        DB::table('users')->where("id", "100002")->delete();
        DB::table('users')->where("id", "100003")->delete();
        DB::table('users')->where("id", "100004")->delete();
        DB::table('users')->where("id", "100005")->delete();
        DB::table('users')->where("id", "100006")->delete();
        DB::table('users')->where("id", "100007")->delete();
        DB::table('users')->where("id", "100008")->delete();
        DB::table('users')->where("id", "100009")->delete();
        DB::table('users')->where("id", "100010")->delete();


        //DB::table('users')->where("id",[100001, 100002, 100003, 100004, 100005, 100006, 100007, 100008, 100009, 100010])->delete();


        DB::table('users')->insert([

            ['id' => 100001,
                'username' => 'buyer1',
                'password' => bcrypt('pass'),
                'email' => 'buyer1logistiks@gmail.com',
                'phone' => '9032560958',
                'user_pic' => NULL,
                'is_active' => 1,
                'is_business' => 1,
                'mail_sent' => 1,
                'is_confirmed' => 1,
                'is_approved' => 1,
                'remind_me' => NULL,
                'is_blocked' => 0,
                'is_buyer_paid' => 1,
                'random_key' => NULL,
                'activation_key' => NULL,
                'logo' => NULL,
                'failed_attempts' => 0,
                'last_login' => '',
                'previous_login' => '',
                'current_login' => '',
                'last_ip' => '183.82.108.66',
                'lkp_role_id' => 1,
                'primary_role_id' => 1,
                'secondary_role_id' => 2,
                'last_login_role_id' => '',
                'is_facebook' => '',
                'fb_identifier' => NULL,
                'is_google' => '',
                'google_identifier' => NULL,
                'is_linkedin' => '',
                'linkedin_identifier' => NULL,
                'pannumber' => 'ABCDE1234Y',
                'remember_token' => '',
                'created_by' => 100001,
                'created_at' => '',
                'created_ip' => '61.12.88.166',
                'updated_at' => '',
                'updated_by' => 100001,
                'updated_ip' => '',
                'is_admin' => '',
                'activated_date' => '',
                'marketplace_id' => 4,
                'business_email_id' => 'buyer1logistiks@techwave.net',
                'is_invite_user' => '',
                'is_superadmin' => '',
                'requested_id' => NULL,
                'transact_accept' => '',
                'transact_password' => '',
                'designation' => NULL,
                'is_under_delear' => ''],

            [
                'id' => 100002,
                'username' => 'buyer2',
                'password' => bcrypt('pass'),
                'email' => 'buyer2logistiks@gmail.com',
                'phone' => '7032223732',
                'user_pic' => NULL,
                'is_active' => 1,
                'is_business' => 1,
                'mail_sent' => 1,
                'is_confirmed' => 1,
                'is_approved' => 1,
                'remind_me' => NULL,
                'is_blocked' => 0,
                'is_buyer_paid' => 1,
                'random_key' => NULL,
                'activation_key' => NULL,
                'logo' => NULL,
                'failed_attempts' => 0,
                'last_login' => '',
                'previous_login' => '',
                'current_login' => '',
                'last_ip' => '183.82.108.66',
                'lkp_role_id' => 1,
                'primary_role_id' => 1,
                'secondary_role_id' => 2,
                'last_login_role_id' => '',
                'is_facebook' => '',
                'fb_identifier' => NULL,
                'is_google' => '',
                'google_identifier' => NULL,
                'is_linkedin' => '',
                'linkedin_identifier' => NULL,
                'pannumber' => 'ABCDE1234Y',
                'remember_token' => '',
                'created_by' => 100002,
                'created_at' => '',
                'created_ip' => '61.12.88.166',
                'updated_at' => '',
                'updated_by' => 100002,
                'updated_ip' => '',
                'is_admin' => '',
                'activated_date' => '',
                'marketplace_id' => 4,
                'business_email_id' => 'buyer2logistiks@techwave.net',
                'is_invite_user' => '',
                'is_superadmin' => '',
                'requested_id' => NULL,
                'transact_accept' => '',
                'transact_password' => '',
                'designation' => NULL,
                'is_under_delear' => ''],

            [
                'id' => 100003,
                'username' => 'buyer3',
                'password' => bcrypt('pass'),
                'email' => 'buyer3logistiks@gmail.com',
                'phone' => '7032223732',
                'user_pic' => NULL,
                'is_active' => 1,
                'is_business' => 1,
                'mail_sent' => 1,
                'is_confirmed' => 1,
                'is_approved' => 1,
                'remind_me' => NULL,
                'is_blocked' => 0,
                'is_buyer_paid' => 1,
                'random_key' => NULL,
                'activation_key' => NULL,
                'logo' => NULL,
                'failed_attempts' => 0,
                'last_login' => '',
                'previous_login' => '',
                'current_login' => '',
                'last_ip' => '183.82.108.66',
                'lkp_role_id' => 1,
                'primary_role_id' => 1,
                'secondary_role_id' => 2,
                'last_login_role_id' => '',
                'is_facebook' => '',
                'fb_identifier' => NULL,
                'is_google' => '',
                'google_identifier' => NULL,
                'is_linkedin' => '',
                'linkedin_identifier' => NULL,
                'pannumber' => 'ABCDE1234Y',
                'remember_token' => '',
                'created_by' => 100003,
                'created_at' => '',
                'created_ip' => '61.12.88.166',
                'updated_at' => '',
                'updated_by' => 100003,
                'updated_ip' => '',
                'is_admin' => '',
                'activated_date' => '',
                'marketplace_id' => 4,
                'business_email_id' => 'buyer3logistiks@techwave.net',
                'is_invite_user' => '',
                'is_superadmin' => '',
                'requested_id' => NULL,
                'transact_accept' => '',
                'transact_password' => '',
                'designation' => NULL,
                'is_under_delear' => ''],

            [
                'id' => 100004,
                'username' => 'buyer4',
                'password' => bcrypt('pass'),
                'email' => 'buyer4logistiks@gmail.com',
                'phone' => '7032223732',
                'user_pic' => NULL,
                'is_active' => 1,
                'is_business' => 1,
                'mail_sent' => 1,
                'is_confirmed' => 1,
                'is_approved' => 1,
                'remind_me' => NULL,
                'is_blocked' => 0,
                'is_buyer_paid' => 1,
                'random_key' => NULL,
                'activation_key' => NULL,
                'logo' => NULL,
                'failed_attempts' => 0,
                'last_login' => '',
                'previous_login' => '',
                'current_login' => '',
                'last_ip' => '183.82.108.66',
                'lkp_role_id' => 1,
                'primary_role_id' => 1,
                'secondary_role_id' => 2,
                'last_login_role_id' => '',
                'is_facebook' => '',
                'fb_identifier' => NULL,
                'is_google' => '',
                'google_identifier' => NULL,
                'is_linkedin' => '',
                'linkedin_identifier' => NULL,
                'pannumber' => 'ABCDE1234Y',
                'remember_token' => '',
                'created_by' => 100004,
                'created_at' => '',
                'created_ip' => '61.12.88.166',
                'updated_at' => '',
                'updated_by' => 100004,
                'updated_ip' => '',
                'is_admin' => '',
                'activated_date' => '',
                'marketplace_id' => 4,
                'business_email_id' => 'buyer4logistiks@techwave.net',
                'is_invite_user' => '',
                'is_superadmin' => '',
                'requested_id' => NULL,
                'transact_accept' => '',
                'transact_password' => '',
                'designation' => NULL,
                'is_under_delear' => ''],

            [
                'id' => 100005,
                'username' => 'buyer5',
                'password' => bcrypt('pass'),
                'email' => 'buyer5logistiks@gmail.com',
                'phone' => '7032223732',
                'user_pic' => NULL,
                'is_active' => 1,
                'is_business' => 1,
                'mail_sent' => 1,
                'is_confirmed' => 1,
                'is_approved' => 1,
                'remind_me' => NULL,
                'is_blocked' => 0,
                'is_buyer_paid' => 1,
                'random_key' => NULL,
                'activation_key' => NULL,
                'logo' => NULL,
                'failed_attempts' => 0,
                'last_login' => '',
                'previous_login' => '',
                'current_login' => '',
                'last_ip' => '183.82.108.66',
                'lkp_role_id' => 1,
                'primary_role_id' => 1,
                'secondary_role_id' => 2,
                'last_login_role_id' => '',
                'is_facebook' => '',
                'fb_identifier' => NULL,
                'is_google' => '',
                'google_identifier' => NULL,
                'is_linkedin' => '',
                'linkedin_identifier' => NULL,
                'pannumber' => 'ABCDE1234Y',
                'remember_token' => '',
                'created_by' => 100005,
                'created_at' => '',
                'created_ip' => '61.12.88.166',
                'updated_at' => '',
                'updated_by' => 100005,
                'updated_ip' => '',
                'is_admin' => '',
                'activated_date' => '',
                'marketplace_id' => '',
                'business_email_id' => 'buyer5logistiks@techwave.net',
                'is_invite_user' => '',
                'is_superadmin' => '',
                'requested_id' => NULL,
                'transact_accept' => '',
                'transact_password' => '',
                'designation' => NULL,
                'is_under_delear' => ''],


            [
                'id' => 100006,
                'username' => 'seller1',
                'password' => bcrypt('pass'),
                'email' => 'seller1logistiks@gmail.com',
                'phone' => '7032223732',
                'user_pic' => NULL,
                'is_active' => 1,
                'is_business' => 1,
                'mail_sent' => 1,
                'is_confirmed' => 1,
                'is_approved' => 1,
                'remind_me' => NULL,
                'is_blocked' => 0,
                'is_buyer_paid' => 1,
                'random_key' => NULL,
                'activation_key' => NULL,
                'logo' => NULL,
                'failed_attempts' => 0,
                'last_login' => '',
                'previous_login' => '',
                'current_login' => '',
                'last_ip' => '183.82.108.66',
                'lkp_role_id' => 2,
                'primary_role_id' => 2,
                'secondary_role_id' => 1,
                'last_login_role_id' => '',
                'is_facebook' => '',
                'fb_identifier' => NULL,
                'is_google' => '',
                'google_identifier' => NULL,
                'is_linkedin' => '',
                'linkedin_identifier' => NULL,
                'pannumber' => 'ABCDE1234Y',
                'remember_token' => '',
                'created_by' => 100006,
                'created_at' => '',
                'created_ip' => '61.12.88.166',
                'updated_at' => '',
                'updated_by' => 100006,
                'updated_ip' => '',
                'is_admin' => '',
                'activated_date' => '',
                'marketplace_id' => '',
                'business_email_id' => 'seller1logistiks@techwave.net',
                'is_invite_user' => '',
                'is_superadmin' => '',
                'requested_id' => NULL,
                'transact_accept' => '',
                'transact_password' => '',
                'designation' => NULL,
                'is_under_delear' => ''],

            [
                'id' => 100007,
                'username' => 'seller2',
                'password' => bcrypt('pass'),
                'email' => 'seller2logistiks@gmail.com',
                'phone' => '7032223732',
                'user_pic' => NULL,
                'is_active' => 1,
                'is_business' => 1,
                'mail_sent' => 1,
                'is_confirmed' => 1,
                'is_approved' => 1,
                'remind_me' => NULL,
                'is_blocked' => 0,
                'is_buyer_paid' => 1,
                'random_key' => NULL,
                'activation_key' => NULL,
                'logo' => NULL,
                'failed_attempts' => 0,
                'last_login' => '',
                'previous_login' => '',
                'current_login' => '',
                'last_ip' => '183.82.108.66',
                'lkp_role_id' => 2,
                'primary_role_id' => 2,
                'secondary_role_id' => 1,
                'last_login_role_id' => '',
                'is_facebook' => '',
                'fb_identifier' => NULL,
                'is_google' => '',
                'google_identifier' => NULL,
                'is_linkedin' => '',
                'linkedin_identifier' => NULL,
                'pannumber' => 'ABCDE1234Y',
                'remember_token' => '',
                'created_by' => 100007,
                'created_at' => '',
                'created_ip' => '61.12.88.166',
                'updated_at' => '',
                'updated_by' => 1000017,
                'updated_ip' => '',
                'is_admin' => '',
                'activated_date' => '',
                'marketplace_id' => '',
                'business_email_id' => 'seller2logistiks@techwave.net',
                'is_invite_user' => '',
                'is_superadmin' => '',
                'requested_id' => NULL,
                'transact_accept' => '',
                'transact_password' => '',
                'designation' => NULL,
                'is_under_delear' => ''],

            [
                'id' => 100008,
                'username' => 'seller3',
                'password' => bcrypt('pass'),
                'email' => 'seller3logistiks@gmail.com',
                'phone' => '7032223732',
                'user_pic' => NULL,
                'is_active' => 1,
                'is_business' => 1,
                'mail_sent' => 1,
                'is_confirmed' => 1,
                'is_approved' => 1,
                'remind_me' => NULL,
                'is_blocked' => 0,
                'is_buyer_paid' => 1,
                'random_key' => NULL,
                'activation_key' => NULL,
                'logo' => NULL,
                'failed_attempts' => 0,
                'last_login' => '',
                'previous_login' => '',
                'current_login' => '',
                'last_ip' => '183.82.108.66',
                'lkp_role_id' => 2,
                'primary_role_id' => 2,
                'secondary_role_id' => 1,
                'last_login_role_id' => '',
                'is_facebook' => '',
                'fb_identifier' => NULL,
                'is_google' => '',
                'google_identifier' => NULL,
                'is_linkedin' => '',
                'linkedin_identifier' => NULL,
                'pannumber' => 'ABCDE1234Y',
                'remember_token' => '',
                'created_by' => 100008,
                'created_at' => '',
                'created_ip' => '61.12.88.166',
                'updated_at' => '',
                'updated_by' => 100008,
                'updated_ip' => '',
                'is_admin' => '',
                'activated_date' => '',
                'marketplace_id' => '',
                'business_email_id' => 'seller3logistiks@techwave.net',
                'is_invite_user' => '',
                'is_superadmin' => '',
                'requested_id' => NULL,
                'transact_accept' => '',
                'transact_password' => '',
                'designation' => NULL,
                'is_under_delear' => ''],

            [
                'id' => 100009,
                'username' => 'seller4',
                'password' => bcrypt('pass'),
                'email' => 'seller4logistiks@gmail.com',
                'phone' => '7032223732',
                'user_pic' => NULL,
                'is_active' => 1,
                'is_business' => 1,
                'mail_sent' => 1,
                'is_confirmed' => 1,
                'is_approved' => 1,
                'remind_me' => NULL,
                'is_blocked' => 0,
                'is_buyer_paid' => 1,
                'random_key' => NULL,
                'activation_key' => NULL,
                'logo' => NULL,
                'failed_attempts' => 0,
                'last_login' => '',
                'previous_login' => '',
                'current_login' => '',
                'last_ip' => '183.82.108.66',
                'lkp_role_id' => 2,
                'primary_role_id' => 2,
                'secondary_role_id' => 1,
                'last_login_role_id' => '',
                'is_facebook' => '',
                'fb_identifier' => NULL,
                'is_google' => '',
                'google_identifier' => NULL,
                'is_linkedin' => '',
                'linkedin_identifier' => NULL,
                'pannumber' => 'ABCDE1234Y',
                'remember_token' => '',
                'created_by' => 100009,
                'created_at' => '',
                'created_ip' => '61.12.88.166',
                'updated_at' => '',
                'updated_by' => 100009,
                'updated_ip' => '',
                'is_admin' => '',
                'activated_date' => '',
                'marketplace_id' => '',
                'business_email_id' => 'seller4logistiks@techwave.net',
                'is_invite_user' => '',
                'is_superadmin' => '',
                'requested_id' => NULL,
                'transact_accept' => '',
                'transact_password' => '',
                'designation' => NULL,
                'is_under_delear' => ''],

            [
                'id' => 100010,
                'username' => 'seller5',
                'password' => bcrypt('pass'),
                'email' => 'seller5logistiks@gmail.com',
                'phone' => '7032223732',
                'user_pic' => NULL,
                'is_active' => 1,
                'is_business' => 1,
                'mail_sent' => 1,
                'is_confirmed' => 1,
                'is_approved' => 1,
                'remind_me' => NULL,
                'is_blocked' => 0,
                'is_buyer_paid' => 1,
                'random_key' => NULL,
                'activation_key' => NULL,
                'logo' => NULL,
                'failed_attempts' => 0,
                'last_login' => '',
                'previous_login' => '',
                'current_login' => '',
                'last_ip' => '183.82.108.66',
                'lkp_role_id' => 2,
                'primary_role_id' => 2,
                'secondary_role_id' => 1,
                'last_login_role_id' => '',
                'is_facebook' => '',
                'fb_identifier' => NULL,
                'is_google' => '',
                'google_identifier' => NULL,
                'is_linkedin' => '',
                'linkedin_identifier' => NULL,
                'pannumber' => 'ABCDE1234Y',
                'remember_token' => '',
                'created_by' => 100010,
                'created_at' => '',
                'created_ip' => '',
                'updated_at' => '',
                'updated_by' => 100010,
                'updated_ip' => '61.12.88.166',
                'is_admin' => '',
                'activated_date' => '',
                'marketplace_id' => 4,
                'business_email_id' => 'seller5logistiks@techwave.net',
                'is_invite_user' => '',
                'is_superadmin' => '',
                'requested_id' => NULL,
                'transact_accept' => '',
                'transact_password' => '',
                'designation' => NULL,
                'is_under_delear' => '']


        ]);
        echo "Success";
    }
}
